// Author: Codex app agent, 2026-09-11.
import {convertSVG} from './svg-convert.js';import {shapeZIP,download} from './file-formats.js';
const $=id=>document.getElementById(id);let text,result;
const disable=()=>{result=null;for(const id of ['geojson','shapefile','open-app'])$(id).disabled=true;};
$('svg-file').onchange=async e=>{disable();try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('SVG exceeds 1 MB');text=await file.text();$('convert').disabled=false;$('status').textContent='File loaded locally. Convert to inspect supported geometry.';}catch(e){$('status').textContent=e.message;}};
$('svg-size').oninput=disable;
$('convert').onclick=()=>{disable();try{result=convertSVG(text,Number($('svg-size').value));const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',result.json.features[0].geometry.coordinates.map(p=>p.map(r=>'M'+r.map(([x,y])=>`${x},${-y}`).join('L')+'Z').join('')).join(''));p.setAttribute('fill-rule','evenodd');p.setAttribute('fill','#25838a');p.setAttribute('stroke','#134d53');p.setAttribute('stroke-width','.06');$('preview').replaceChildren(p);const size=Number($('svg-size').value)*1.1;$('preview').setAttribute('viewBox',`${-size/2} ${-size/2} ${size} ${size}`);$('warnings').textContent=result.warnings.join('\n');$('status').textContent=`Converted ${result.vertices} sampled vertices. Review ${result.warnings.length?'warnings and ':''}the polygon preview.`;for(const id of ['geojson','shapefile','open-app'])$(id).disabled=false;}catch(e){$('status').textContent='Conversion failed: '+e.message;$('preview').replaceChildren();}};
$('geojson').onclick=()=>download(JSON.stringify(result.json),'drawing.geojson','application/geo+json');$('shapefile').onclick=()=>download(shapeZIP(result.json),'drawing.zip','application/zip');
$('open-app').onclick=()=>{try{const data=JSON.stringify({version:1,created:Date.now(),json:result.json});if(data.length>2000000)throw Error('Use a file download for this large drawing');const keys=Object.keys(localStorage).filter(k=>k.startsWith('shp2stl.transfer.'));while(keys.length>=3)localStorage.removeItem(keys.shift());const id=crypto.randomUUID();localStorage.setItem('shp2stl.transfer.'+id,data);$('handoff').textContent='Drawing prepared locally. The app will acknowledge after validating and creating it.';const a=document.createElement('a');a.href='app.html?drawing='+id;a.target='_blank';a.rel='noopener';a.click();const timer=setInterval(()=>{if(localStorage.getItem('shp2stl.ack.'+id)){localStorage.removeItem('shp2stl.ack.'+id);$('handoff').textContent='SHP2STL acknowledged the drawing and created the model.';clearInterval(timer);}},500);setTimeout(()=>clearInterval(timer),120000);}catch(e){$('handoff').textContent=e.message;}};
